name: ChatOps
on:
  issue_comment:
    types: [ created,updated ] 
    
jobs:
  command:
    runs-on: ubuntu-latest    
    steps:
    - run: |
        echo ${{ toJson(github.event.comment) }}
    - uses: peter-evans/repository-dispatch@v1
      if: contains(github.event.comment.body, '/deploy')
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: release-to-qa
        client-payload: '{ "env": "qa" }'
