name: ChatOps
on:
  issue_comment:
    types: [ created,updated ] 
    
jobs:
  command:
    runs-on: ubuntu-latest    
    steps:
    - uses: peter-evans/repository-dispatch@v1
      if: contains(github.event.comment.body, '/deploy-qa')
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: release-to-env
        client-payload: '{ "tag": "v11","prerelease": true }'
    - uses: peter-evans/repository-dispatch@v1
      if: contains(github.event.comment.body, '/deploy-prod')
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: release-to-env
        client-payload: '{ "tag": "v11","prerelease": false }'
