name: Build and Deploy in Staging
on:
  push:
    branches: [ master ]

    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
        
  build:
    name: Build
    if: github.event.action != 'released'
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "test"
