name: Release to env
on:
  repository_dispatch:
    types: [release-to-env]
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo ${{ toJSON(github.event) }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.client_payload.tag }}
          prerelease: ${{ github.event.client_payload.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
